export let products = [
    {
        name: "Arroz",
        price: 800,
        stock: 20,
        description: "Arroz integral ...",
        category: "cereales",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1688663707/ADN-Rosario/arroz_m9knbl.webp",
    },
    {
        name: "Avena",
        price: 750,
        stock: 10,
        description: "Avena marca Quaker fuente de fibra alimentaria",
        category: "cereales",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1688664264/ADN-Rosario/avena_h1rebt.png",
    },
    {
        name: "Almohaditas",
        price: 50,
        stock: 25,
        description: "Almohaditas de limon ....",
        category: "cereales",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777463/Almohaditas-limon_qggmze.jpg",
    },
    {
        name: "Lentejas",
        price: 1200,
        stock: 25,
        description: "1kg de lentejas de ..",
        category: "legumbres",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1688664363/ADN-Rosario/lentejas_dhtxu4.jpg",
    },
    {
        name: "Garbanzos",
        price: 1000,
        stock: 15,
        description: "1kg de garbanzos de ...",
        category: "legumbres",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1688664293/ADN-Rosario/garbanzos_wnl2bf.jpg",
    },
    {
        name: "Porotos",
        price: 1000,
        stock: 8,
        description: "x cantidad de porotos negros....",
        category: "legumbres",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777213/porotos_pa8vry.jpg",
    },
    {
        name: "Aji molido",
        price: 300,
        stock: 30,
        description: "200g de aji molido de...",
        category: "condimentos",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1688664449/ADN-Rosario/ajiMolido_xkqfai.jpg",
    },
    {
        name: "Comino",
        price: 400,
        stock: 40,
        description: "200g de comino de...",
        category: "condimentos",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1688664442/ADN-Rosario/comino_vd3k74.jpg",
    },
    {
        name: "Pimentón",
        price: 350,
        stock: 27,
        description: "200g de pimentón ...",
        category: "condimentos",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777104/pimenton_htynlw.jpg",
    },
    {
        name: "Chía",
        price: 280,
        stock: 36,
        description: "Bolsa de 150g de semillas de chía",
        category: "semillas",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777452/chia_sviu7m.jpg",
    },
    {
        name: "Girasol",
        price: 360,
        stock: 12,
        description: "Bolsa de 150g de semillas de girasol",
        category: "semillas",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777446/girasol_payhqb.jpg",
    },
    {
        name: "Lino",
        price: 420,
        stock: 23,
        description: "Bolsa de 150g de semillas de lino",
        category: "semillas",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777438/lino_sgqlth.jpg",
    },
    {
        name: "Almendras",
        price: 890,
        stock: 17,
        description: "250g de Almendras ...",
        category: "frutos-secos",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777468/almendras_eu6fcy.jpg",
    },
    {
        name: "Castañas",
        price: 1000,
        stock: 6,
        description: "250g de Castañas de Cajú ...",
        category: "frutos-secos",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777458/casta%C3%B1as_de_caju_u1k8oy.jpg",
    },
    {
        name: "Nueces",
        price: 950,
        stock: 19,
        description: "250g de Nueces...",
        category: "frutos-secos",
        img: "https://res.cloudinary.com/dqpt6x98p/image/upload/v1698777240/nueces_brdzpw.jpg",
    },
]